# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ea6645636d6bfee9f8e3fd4b235ea913dece2eabe753890befa7ba664546c715fa914609ae50692c8a8084912c60eaef9d3dba85c74854ba0c991f280388c2a

test:
  secret_key_base: 176a3f3848995dbc08cdac006db12a02cd5a13560da583a046fb30a3ec7f1ea682652057222d107cb8a7f0ed698b03aab7fb422c67ad686cdda3f24c253a26fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
